from tkinter import *
a=Tk()
L=Label(a,text="registration form:",font="verdana 22",relief="raised")
L.grid(row=0,column=1)
l=Label(a,text="enter name",font="verdana 16",relief="groove",bd=4)
l.grid(row=1,column=0,padx=10,pady=10)
e=Entry(a,font="verdana 16",relief="sunken",bd=4)
e.grid(row=1,column=1)
l1=Label(a,text="enter your address",font="verdana 16",bd=4,relief="groove")
l1.grid(row=2,column=0)
e1=Entry(a,font="verdana 16",relief="sunken",bd=4)
e1.grid(row=2,column=1)
l2=Label(a,text="select your gender",font="verdana 16",bd=4,relief="groove")
l2.grid(row=3,column=0,pady=10)
v=IntVar()
Radiobutton(text="male",value=1,variable=v).grid(row=3,column=1,)
Radiobutton(text="female",value=2,variable=v).grid(row=4,column=1,pady=15)
Radiobutton(text="other",value=3,variable=v).grid(row=5,column=1,)
b1=Button(a,text="save",font="verdana 16",relief="groove",bd=4)
b1.grid(row=6,column=0,padx=10,pady=10)
a.geometry("500x500")
a.config(bg="light blue")
a.mainloop()
